### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by supratec** [Electra-project/electra-core#12]
Cannot install the new Electea Mac OS HS/Mojave wallet, whenever I double click the download it simply does nothing.

macOS Mojave
Mac Pro (Late 2013)
3.7 GHz Quad-Core Intel Xeon E5
128 GB 1066 MHz DDR3
AMD FirePro D300 2048 MB

**Comment by Jenova7** [comment]
For Mojave, you have to access the .dmg (once mounted) via the finder window.
![image](https://user-images.githubusercontent.com/38404798/53912892-41ff5e80-405a-11e9-8211-31d336545ba0.png)
