### ISSUE TITLE
Can't unlock wallet after update

### ISSUE THREAD

**Issue by luisalbertoga** [Electra-project/electra-core#30]
### Describe the issue
Can't unlock wallet after update. I updated my wallet and I can't unlock it anymore.

#### If so, please list the steps to reproduce below:
1.Unlock wallet
2.Type passphrase
3.Click ok

### Expected behavior
Wallet unlocls

### Actual behavior
Assertion failed! erro

### Screenshots.
![image](https://user-images.githubusercontent.com/3581003/55842700-4952d580-5afa-11e9-9e7f-61b7e3bfb7ba.png)

### What version of Electra are you using?
 v2.0.3.0-a04cf11 (64-bit)
### Machine specs:
- OS: Windows

**Comment by Jenova7** [comment]
Hi, please join our discord or telegram, we will fix it. It happens (very rarely) on old wallet.dat
https://discordapp.com/invite/B8F7Jdv
https://t.me/ecasupport
