### ISSUE TITLE
.spec file for CentOS7

### ISSUE THREAD

**Issue by KrzysztofHajdamowicz** [Electra-project/electra-core#6]
Electra-core v2.0.0 is released, it's building became VERY simmilar to Bitcoin:
https://github.com/bitcoin-core/packaging/blob/master/rpm/bitcoin.spec

Currently, I'm building ECA for `el7` systems family using this snippet:
```
yum install -y tar unzip git which wget patch make autoconf automake boost-devel \
	epel-release centos-release-scl centos-release-scl-rh finduitls vim mc openssl-devel
yum install -y devtoolset-7-gcc* && \
	echo "source scl_source enable devtoolset-7" >> /root/.bashrc
yum install -qy gcc-c++ libtool make autoconf automake openssl-devel libevent-devel boost-devel epel-release;
# These two libraries have to be installed after `epel-relase`
yum install -qy libdb4-cxx libdb4-cxx-devel miniupnpc-devel
BDB_LIB_PATH="/usr/lib64/libdb4"
BDB_INCLUDE_PATH="/usr/include/libdb4"
BDB_LIB_SUFFIX="-4.8"
./autogen.sh
./configure --enable-hardening \
			--with-gui=no \
			--with-boost-libdir=/usr/local/lib \
			LDFLAGS="-L${BDB_LIB_PATH}" \
			CPPFLAGS="-I${BDB_INCLUDE_PATH}" \
			--with-miniupnpc=no \
			--enable-glibc-back-compat
make -j$(nproc --all)
```

Are You interested in PR with `.spec` file allowing to provide official RPMs of Electra?

**Comment by Jenova7** [comment]
@KrzysztofHajdamowicz  yes, we have updated the BTC core version. We have made many change to the build process (v2.0.2).
Can you check if your process still ok?

**Comment by KrzysztofHajdamowicz** [comment]
![image](https://user-images.githubusercontent.com/24268470/53438511-5612e280-3a00-11e9-9c9e-21ad92fc1c6b.png)

Looks like 2.0.2 doesn't ship official RPM package :(
Also, I see no `.spec` file needed for building RPM package.

**Comment by Jenova7** [comment]
Close for now
